export const Messages = {
    success: 'Success',
    userExists: 'User already exists',
    invalidCredentials: 'Invalid Credentials',
    incorrectPassword: 'Incorrect password',
    internalServerError: 'Internal Server Error',
    userNotFound: 'User not found',
    tokenInvalid: 'Invalid token',
    refreshTokenInvalid: 'Invalid refresh token',
    accessTokenGenerationError: 'Error generating access token',
    userRolesError: 'Could not get user roles',
    userRolesNotAvailable: 'User or user roles not available for access token generation',
    authenticationError: 'Authentication error',
    unauthorizedAccess: 'Unauthorized access',
    expiredToken: 'Expired token, please log in again',
    validationError: 'Validation error',
    invalidInput: 'Invalid input data',
    missingRequiredField: 'Missing required field',
    userCreationError: 'Error creating user',
    userUpdateError: 'Error updating user information',
    userDeletionError: 'Error deleting user',
    userNotAuthorized: 'User not authorized for this action',
    notFoundError: 'Resource not found',
    operationFailed: 'Operation failed',
};
