export const Messages = {
    SUCCESS: 'Success',
    USER_EXISTS: 'User already exists',
    INVALID_CREDENTIALS: 'Invalid Credentials',
    INCORRECT_PASSWORD: 'Incorrect password',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    USER_NOT_FOUND: 'User not found',
    TOKEN_INVALID: 'Invalid token',
    REFRESH_TOKEN_INVALID: 'Invalid refresh token',
    ACCESS_TOKEN_GENERATION_ERROR: 'Error generating access token',
    USER_ROLES_ERROR: 'Could not get user roles',
    USER_ROLES_NOT_AVAILABLE: 'User or user roles not available for access token generation',
    AUTHENTICATION_ERROR: 'Authentication error',
    UNAUTHORIZED_ACCESS: 'Unauthorized access',
    EXPIRED_TOKEN: 'Expired token, please log in again',
    VALIDATION_ERROR: 'Validation error',
    INVALID_INPUT: 'Invalid input data',
    MISSING_REQUIRED_FIELD: 'Missing required field',
    USER_CREATION_ERROR: 'Error creating user',
    USER_UPDATE_ERROR: 'Error updating user information',
    USER_DELETION_ERROR: 'Error deleting user',
    USER_NOT_AUTHORIZED: 'User not authorized for this action',
    NOT_FOUND_ERROR: 'Resource not found',
    OPERATION_FAILED: 'Operation failed',
};
